---
version: 2
builds:
- id: "iam"
  binary: iam
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/iam/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: alphauslabs
    name: iam
brews:
- repository:
    owner: alphauslabs
    name: homebrew-tap
  name: iam
  homepage: "https://github.com/alphauslabs/iam"
  description: "The official command line interface for Alphaus internal IAM service."
  directory: Formula
  install: |
    bin.install "iam"
  test: |
    assert_match /Command line interface for /, shell_output("#{bin}/iam -h", 0)
